# Generated by Django 3.2.11 on 2022-01-09 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainCode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductor',
            name='Bus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MainCode.busregister'),
            preserve_default=False,
        ),
    ]
