# Generated by Django 3.2.11 on 2022-01-18 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainCode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busregister',
            name='RouteId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainCode.route'),
        ),
    ]
